[CmdletBinding()]
param([switch]$SkipSmokeTest)
$ErrorActionPreference = 'Stop'
$scriptDir = Split-Path -Parent $MyInvocation.MyCommand.Path
$resourceRoot = Join-Path $env:USERPROFILE '.exegol\my-resources'
$gpuRoot = Join-Path $resourceRoot 'setup\gpu'
$configPath = Join-Path $gpuRoot 'gpu-host.conf'
$launcherPath = Join-Path $env:USERPROFILE '.exegol\exegol-gpu.ps1'
$shimRoot = Join-Path $env:USERPROFILE '.exegol\gpu-python'
function Fail([string]$Message) { Write-Error "$Message`nSee README.md (Windows / WSL2 + NVIDIA) for remediation steps."; exit 1 }
function Require-Command([string]$Name, [string]$Hint) { if (-not (Get-Command $Name -ErrorAction SilentlyContinue)) { Fail "$Name was not found. $Hint" } }
Write-Host '[*] Checking Windows GPU prerequisites...' -ForegroundColor Cyan
Require-Command 'docker' 'Install Docker Desktop and enable WSL2 integration.'
Require-Command 'exegol' 'Install Exegol with: py -m pip install exegol'
$dockerInfo = docker info 2>&1
if ($LASTEXITCODE -ne 0) { Fail 'Docker Desktop is not running or its WSL2 engine is unavailable.' }
if (($dockerInfo -join "`n") -notmatch 'OSType:\s*linux') { Fail 'Docker Desktop is not using the Linux engine.' }
$wsl = wsl.exe --status 2>&1
if (($wsl -join "`n") -match 'denied|not installed|not found') { Fail 'WSL2 is not available for this user.' }

# Docker Desktop uses the WSL distro mount service for bind mounts. Keep the
# user's Debian distro running so its guest-services socket is available.
try {
    wsl.exe --distribution Debian --exec true 2>$null
    if ($LASTEXITCODE -ne 0) { Write-Warning 'Debian WSL distro could not be started; Docker Desktop may reject bind mounts.' }
} catch { Write-Warning 'Debian WSL distro could not be started; Docker Desktop may reject bind mounts.' }
if (-not $SkipSmokeTest) {
    Write-Host '[*] Running NVIDIA Docker smoke test...' -ForegroundColor Cyan
    docker run --rm --gpus all 'nvidia/cuda:12.4.1-base-ubuntu22.04' nvidia-smi
    if ($LASTEXITCODE -ne 0) { Fail 'Docker GPU passthrough failed. Update the NVIDIA Windows driver and Docker Desktop.' }
}
New-Item -ItemType Directory -Force -Path $gpuRoot | Out-Null
New-Item -ItemType Directory -Force -Path $shimRoot | Out-Null
Copy-Item (Join-Path $scriptDir 'setup-gpu.sh') (Join-Path $gpuRoot 'setup-gpu.sh') -Force
$gpuName = 'Windows NVIDIA GPU'
if (-not $SkipSmokeTest) { try { $gpuName = (docker run --rm --gpus all 'nvidia/cuda:12.4.1-base-ubuntu22.04' nvidia-smi --query-gpu=name --format=csv,noheader 2>$null | Select-Object -First 1).Trim() } catch {} }
@("# Generated by install-gpu-windows.ps1", "HOST_GPU_NAME='$gpuName'", "HOST_DRIVER_VERSION='docker-desktop'", "HOST_CUDA_VERSION='12.x'", "HOST_COMPUTE_CAP=''", "HOST_GPU_MEM=''") | Set-Content -Encoding utf8 $configPath
@'
import os

if os.environ.get("EXEGOL_GPU_RUNTIME") == "nvidia":
    from docker.models.containers import ContainerCollection

    if not getattr(ContainerCollection.create, "_exegol_gpu_patched", False):
        _create = ContainerCollection.create

        def _gpu_create(self, *args, **kwargs):
            kwargs.setdefault("runtime", "nvidia")
            return _create(self, *args, **kwargs)

        _gpu_create._exegol_gpu_patched = True
        ContainerCollection.create = _gpu_create
'@ | Set-Content -Encoding utf8 (Join-Path $shimRoot 'sitecustomize.py')
@'
[CmdletBinding()]
param([Parameter(ValueFromRemainingArguments=$true)][string[]]$Arguments)
$env:PYTHONIOENCODING = 'utf-8'
$env:PYTHONUTF8 = '1'
$env:EXEGOL_GPU_RUNTIME = 'nvidia'
$shim = Join-Path $env:USERPROFILE '.exegol\gpu-python'
if ($env:PYTHONPATH) { $env:PYTHONPATH = "$shim;$env:PYTHONPATH" } else { $env:PYTHONPATH = $shim }
$gpuArgs = @('--privileged', '--network', 'docker', '--disable-shared-timezones', '--env', 'NVIDIA_VISIBLE_DEVICES=all', '--env', 'NVIDIA_DRIVER_CAPABILITIES=compute,utility')
& exegol @Arguments @gpuArgs
exit $LASTEXITCODE
'@ | Set-Content -Encoding utf8 $launcherPath
Write-Host "[+] GPU resources installed in $gpuRoot" -ForegroundColor Green
Write-Host "[+] Use: powershell -ExecutionPolicy Bypass -File `"$launcherPath`" start mybox full" -ForegroundColor Green
